### ISSUE TITLE
Cannot query for document of more than 16777216 (2^24) bytes

### ISSUE THREAD

**Issue by no-man-is-an-island** [NHSDigital/integration-adaptor-gp2gp#389]
Affects version:

gp2gp: 1.3.1

When requesting a document (in our case 20MB) larger than 16MB the following error is thrown when trying to pull the response body from the gpc adapter:

```
Thread="DefaultMessageListenerContainer-1" Message="An error occurred while handing a task message ID:94adb384-6093-4f91-a10d-036bb971a273:2:1:1-1"

org.springframework.web.reactive.function.client.WebClientResponseException: 200 OK from GET http://gpcc:8090/gpc/N82103/Binary/418cd8ff-483a-40d1-9418-153b29c4fee0; nested exception is org.springframework.core.io.buffer.DataBufferLimitException: Exceeded limit on max bytes to buffer : 16777216

at org.springframework.web.reactive.function.client.WebClientResponseException.create(WebClientResponseException.java:229)

at org.springframework.web.reactive.function.client.DefaultClientResponse.lambda$createException$1(DefaultClientResponse.java:213)

at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:106)

at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)

at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2397)

at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2193)

at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onSubscribe(FluxOnErrorResume.java:74)

at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54)

at reactor.core.publisher.Mono.subscribe(Mono.java:4150)

at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103)

at reactor.core.publisher.Operators$MonoSubscriber.onError(Operators.java:1862)

at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onError(FluxMapFuseable.java:140)

at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onError(FluxContextWrite.java:121)

at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onError(FluxMapFuseable.java:334)

at reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber.onError(FluxFilterFuseable.java:382)

at reactor.core.publisher.MonoCollect$CollectSubscriber.onError(MonoCollect.java:144)

at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onError(FluxOnAssembly.java:392)

at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:132)

at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:221)

at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:132)

at reactor.core.publisher.Operators.error(Operators.java:197)

at reactor.netty.channel.FluxReceive.startReceiver(FluxReceive.java:183)

at reactor.netty.channel.FluxReceive.subscribe(FluxReceive.java:144)

at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62)

at reactor.netty.ByteBufFlux.subscribe(ByteBufFlux.java:340)

at reactor.core.publisher.Mono.subscribe(Mono.java:4150)

at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103)

at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onError(FluxOnAssembly.java:392)

at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onError(FluxMapFuseable.java:140)

at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onError(FluxContextWrite.java:121)

at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onError(FluxMapFuseable.java:334)

at reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber.onError(FluxFilterFuseable.java:382)

at reactor.core.publisher.MonoCollect$CollectSubscriber.onError(MonoCollect.java:144)

at reactor.core.publisher.MonoCollect$CollectSubscriber.onNext(MonoCollect.java:123)

at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:120)

at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:199)

at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:120)

at reactor.netty.channel.FluxReceive.onInboundNext(FluxReceive.java:365)

at reactor.netty.channel.ChannelOperations.onInboundNext(ChannelOperations.java:405)

at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:707)

at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:94)

at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)

at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)

at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)

at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)

at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)

at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)

at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)

at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)

at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)

at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)

at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)

at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)

at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)

at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)

at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)

at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)

at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)

at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)

at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)

at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

at java.base/java.lang.Thread.run(Unknown Source)

Suppressed: java.lang.Exception: #block terminated with an error

at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)

at reactor.core.publisher.Mono.block(Mono.java:1703)

at uk.nhs.adaptors.gp2gp.gpc.GpcClient.performRequest(GpcClient.java:53)

at uk.nhs.adaptors.gp2gp.gpc.GpcClient.getDocumentRecord(GpcClient.java:40)

at uk.nhs.adaptors.gp2gp.gpc.GetGpcDocumentTaskExecutor.execute(GetGpcDocumentTaskExecutor.java:32)

at uk.nhs.adaptors.gp2gp.gpc.GetGpcDocumentTaskExecutor.execute(GetGpcDocumentTaskExecutor.java:12)

at uk.nhs.adaptors.gp2gp.common.task.TaskHandler.executeTask(TaskHandler.java:76)

at uk.nhs.adaptors.gp2gp.common.task.TaskHandler.handle(TaskHandler.java:40)

at uk.nhs.adaptors.gp2gp.common.task.TaskConsumer.receive(TaskConsumer.java:28)

at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

at java.base/java.lang.reflect.Method.invoke(Unknown Source)

at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:171)

at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:120)

at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:114)

at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.onMessage(MessagingMessageListenerAdapter.java:77)

at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:736)

at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:696)

at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:674)

at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:318)

at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:257)

at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1189)

at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1179)

at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1076)

... 1 common frames omitted
```

**Comment by adrianclay** [comment]
Resolved in #562
